
version: '3.8'
services:
  db:
    image: mysql:8.0
    # restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql